# Generated by Django 2.2.6 on 2019-11-02 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nahidapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='number',
            field=models.ImageField(default=1, upload_to=''),
        ),
    ]
